definitions:
  models.SignInRequest:
    properties:
      password:
        example: Goat@018
        maxLength: 20
        minLength: 8
        type: string
      username:
        example: virat
        type: string
    required:
    - password
    - username
    type: object
info:
  contact: {}
paths:
  /v1/signin:
    post:
      consumes:
      - application/json
      description: Handle sign-in request and authenticate the user
      parameters:
      - description: Sign-in request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.SignInRequest'
      produces:
      - application/json
      responses:
        "200":
          description: User authenticated successfully
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
      summary: Handle sign-in request
swagger: "2.0"
